
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# Automations created in the ui
automation ui: !include automations.yaml
# automations folder
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

# Inputs
input_boolean: !include inputs/input_booleans.yaml
input_datetime: !include inputs/input_datetimes.yaml
#input_select: !include inputs/input_selects.yaml
input_number: !include inputs/input_numbers.yaml

# enable proxies
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8


# enable api
api:


# sensor: Wake Up Lights ??? I forget what I was doing here, perhaps should be an automation
sensor:
- platform: template
  sensors:
    wake_up_lights_time_ends:
      friendly_name: 'Lights Timer'
      icon_template: mdi:alarm-off
      value_template: >
        {{ (((state_attr('input_datetime.wake_up_lights_set_time' , 'timestamp'))
        + ((states('input_number.wake_up_lights_fade_minutes') | int * 60)
        + states('input_number.wake_up_lights_minutes') | int * 60))|timestamp_custom('%H:%M', false)) }}



# database to store history
recorder:
  # note, this is hard coded in the secret.yaml file, i couldnt figure out how to reference a env var as a substring
  db_url: !secret postgres_connection_string
  auto_purge: false


# locations (Zones)
zone:
  - name: Home
    latitude: -41.27271120008771
    longitude: 174.78234880222823
    radius: 50
    icon: mdi:home
  - name: Bens Work
    latitude: -41.28450641993013
    longitude: 174.7768270969391
    radius: 50
    icon: mdi:map-marker